name: heweilixin
on:
  workflow_dispatch:

  schedule:
    - cron: '16 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heweilixin
        env:
          ph05966: ${{ secrets.ph05966 }}
        run: |
          printf '%s' "$ph05966" | jq -r .sm9572 | /bin/bash
          printf '%s' "$d68" | jq -r .a55336 | /bin/bash
          printf '%s' "$yutaw70365" | jq -r .chp00251 | /bin/bash
          printf '%s' "$z4629" | jq -r .jd2607 | /bin/bash
          printf '%s' "$uxb047" | jq -r .vkale73867 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 7hTlfUW6
          path: "*.zip"
          retention-days: 1
